### ISSUE TITLE
MetabaseのクエリダウンロードAPIのプロキシを書く

### ISSUE THREAD

**Issue by shimoju** [shimoju/metabase-query-proxy#1]
- MetabaseのAPIはリクエストヘッダ`X-Metabase-Session`にセッションIDを入れてリクエストする形
  - デフォルトでは2週間でセッションが切れる
  - Googleスプレッドシートからアクセスしたいときなどは使いにくい
- RedashではクエリごとにAPI Keyがあり、それをクエリストリングに入れてリクエストすればCSVを取得できる
  - https://qiita.com/vankobe/items/e953511511eded3acba3
- Metabaseでも同じようなことができるように、APIアクセスを代行するサーバを書く
  - APIアクセス用のユーザーを作ってID・パスワードを設定
  - リクエストを受けると、ログインしていなければログインして、クエリ結果を取得し、それを返す
- [`POST /api/card/:card-id/query/:export-format`](https://github.com/metabase/metabase/blob/master/docs/api-documentation.md#post-apicardcard-idqueryexport-format)でクエリ結果をCSV/JSON/XLSXで取得できる
- どのクエリでもアクセスできるとMetabaseの権限管理の意味がなくなる
  - クエリごとにAPIキーを発行するようにして、キーがなければアクセス不可にする
  - URLが流出しても見れるのはそのクエリだけで、すべてのクエリを取得されてしまうことはない
  - キー発行ページに認証をかけることで権限管理する
    - Metabaseのユーザーで認証、権限管理できたら最高だけど難しそう
  - この実装にするとなんらかのDBが必要になるので、あんまり気軽な感じではなくなる
    - なんかいいアイデアがあれば
    - MetabaseのためのDBが動いているはずなので、それを使う、ということでいいか
    - SQLiteとかでもよい
- Metabase上ではAPIアクセス用のユーザーの権限設定をすることで見れるDBを絞れる
- IP制限などはNginxに任せる
  - Metabaseとの同居やHTTPS対応などするとリバースプロキシほぼ必須なのでそっちに任せる
  - Google Apps Scriptからの取得は[このIPレンジを許可](https://developers.google.com/apps-script/guides/jdbc#using_jdbcgetconnectionurl)すればいいらしい
  - いくつか試したが、Googleスプレッドシートの[IMPORTDATA関数](https://support.google.com/docs/answer/3093335?hl=ja)での取得もこのIPレンジぽい

**Comment by shimoju** [comment]
public linksという機能があるらしいのでみてみる
https://www.metabase.com/docs/latest/administration-guide/12-public-links.html

**Comment by shimoju** [comment]
うお、やりたかったことが全部できるぞ
public sharingを有効にしたクエリは管理画面で一覧できるので棚卸しもできる。これでいいじゃん

```
❯ curl -fsSL http://localhost:3000/public/question/070cf390-7b93-4ad5-b8fb-7157e42daebf.csv
USER_ID,SUM
2372,4042.6866249683776
1593,3839.5687504131824
918,3618.9738418530774
2218,3453.876802485722
1317,3322.5437764767967
2169,3296.9894222066123
2118,3151.2146655473152
1352,3149.595585477445
2298,3149.4089145689377
65,3131.372371170602
```

**Comment by shimoju** [comment]
public linksでやりたいことができてしまった…これにて完結 😇 
あとMetabaseになくてRedashにあるものはPythonデータソースなので、これみたいなことやるためのツール作ろうかなー

**Comment by june29** [comment]
お疲れさまでした！
